'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { ArrowRight, Recycle, Search } from 'lucide-react';
import { useState } from 'react';

/* ══════════════════════════════════════
   CATEGORIES DATA
══════════════════════════════════════ */
interface Category {
  slug: string;
  emoji: string;
  name: string;
  desc: string;
  color: string;
  bgColor: string;
  tag: string;
  tagColor: string;
}

const categories: Category[] = [
  {
    slug: 'municipal', emoji: '🏠', name: 'Municipal',
    desc: 'Everyday household and commercial waste — the most familiar waste stream, including food scraps, packaging, and general refuse.',
    color: '#F97316', bgColor: '#F9731615', tag: 'General', tagColor: '#F97316',
  },
  {
    slug: 'industrial', emoji: '🏭', name: 'Industrial',
    desc: 'Manufacturing byproducts, chemical residues, and process waste generated by factories and industrial operations.',
    color: '#64748B', bgColor: '#64748B15', tag: 'Industrial', tagColor: '#64748B',
  },
  {
    slug: 'hazardous', emoji: '⚠️', name: 'Hazardous',
    desc: 'Toxic, flammable, corrosive, or reactive materials that pose serious risk to human health and the environment.',
    color: '#EF4444', bgColor: '#EF444415', tag: 'Danger', tagColor: '#EF4444',
  },
  {
    slug: 'medical', emoji: '🏥', name: 'Medical',
    desc: 'Healthcare facility waste including sharps, infected materials, pharmaceuticals, and biohazardous substances.',
    color: '#EC4899', bgColor: '#EC489915', tag: 'Biohazard', tagColor: '#EC4899',
  },
  {
    slug: 'construction', emoji: '🏗️', name: 'Construction',
    desc: 'Demolition rubble, concrete, timber, drywall, roofing materials, and other debris from building projects.',
    color: '#A78BFA', bgColor: '#A78BFA15', tag: 'Inert', tagColor: '#A78BFA',
  },
  {
    slug: 'agricultural', emoji: '🌾', name: 'Agricultural',
    desc: 'Farm runoff, crop residues, animal manure, pesticide containers, and agri-chemical waste from food production.',
    color: '#84CC16', bgColor: '#84CC1615', tag: 'Organic', tagColor: '#84CC16',
  },
  {
    slug: 'organic', emoji: '🍃', name: 'Organic',
    desc: 'Biodegradable food scraps, yard clippings, and garden waste that can be composted into valuable soil amendment.',
    color: '#00C47D', bgColor: '#00C47D15', tag: 'Compostable', tagColor: '#00C47D',
  },
  {
    slug: 'electronic', emoji: '💻', name: 'Electronic',
    desc: 'Discarded electronics containing toxic heavy metals — the fastest-growing and most under-recycled waste stream globally.',
    color: '#006FEF', bgColor: '#006FEF15', tag: 'E-Waste', tagColor: '#006FEF',
  },
  {
    slug: 'plastic', emoji: '🧴', name: 'Plastic',
    desc: 'Polymer-based packaging, containers, and products — only 9% has ever been recycled in human history.',
    color: '#00B8D9', bgColor: '#00B8D915', tag: 'Recyclable', tagColor: '#00B8D9',
  },
  {
    slug: 'paper', emoji: '📄', name: 'Paper',
    desc: 'Cellulose-based waste including newsprint, cardboard, office paper, and packaging — one of the most successfully recycled materials.',
    color: '#EAB308', bgColor: '#EAB30815', tag: 'Recyclable', tagColor: '#EAB308',
  },
  {
    slug: 'glass', emoji: '🪟', name: 'Glass',
    desc: 'Silica-based waste from bottles, jars, and panes — 100% recyclable indefinitely without quality loss.',
    color: '#22D3EE', bgColor: '#22D3EE15', tag: 'Recyclable', tagColor: '#22D3EE',
  },
  {
    slug: 'metal', emoji: '🔩', name: 'Metal',
    desc: 'Ferrous and non-ferrous scrap including steel, aluminium, copper, and precious metals — among the most valuable recyclables.',
    color: '#6B7280', bgColor: '#6B728015', tag: 'High Value', tagColor: '#8B5CF6',
  },
];

/* ══════════════════════════════════════
   MAIN PAGE
══════════════════════════════════════ */
export default function WasteCategoriesPage() {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<string>('All');

  const tags = ['All', 'General', 'Industrial', 'Danger', 'Biohazard', 'Inert', 'Organic', 'Compostable', 'E-Waste', 'Recyclable', 'High Value'];

  const filtered = categories.filter(c => {
    const matchSearch = c.name.toLowerCase().includes(search.toLowerCase()) ||
      c.desc.toLowerCase().includes(search.toLowerCase());
    const matchFilter = filter === 'All' || c.tag === filter;
    return matchSearch && matchFilter;
  });

  return (
    <main className="overflow-x-hidden">

      {/* ─── HERO ─── */}
      <section className="relative min-h-[65vh] flex items-center justify-center overflow-hidden"
        style={{ background: 'linear-gradient(135deg, #050d1a 0%, #0a1628 60%, #021a0e 100%)' }}>
        <div className="orb orb-green w-[500px] h-[500px] -top-32 -left-20 opacity-30" />
        <div className="orb orb-blue w-[450px] h-[450px] -bottom-24 right-10 opacity-25" />

        {/* Floating emojis */}
        {['🏠', '🏭', '⚠️', '🏥', '🏗️', '🌾', '🍃', '💻', '🧴', '📄', '🪟', '🔩'].map((em, i) => (
          <motion.div key={i}
            className="absolute text-2xl select-none pointer-events-none"
            style={{ top: `${10 + (i * 7.5) % 80}%`, left: `${5 + (i * 8) % 90}%`, opacity: 0.15 }}
            animate={{ y: [0, -15, 0], rotate: [0, 10, -10, 0] }}
            transition={{ duration: 3 + i * 0.4, repeat: Infinity, delay: i * 0.3 }}>
            {em}
          </motion.div>
        ))}

        <div className="relative z-10 text-center container-lg">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}
            className="label-tag mx-auto mb-6 w-fit">
            <Recycle className="w-4 h-4" /> Waste Classification
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.1 }}
            className="heading-hero text-white mb-5">
            Understanding{' '}
            <span className="gradient-text">Waste Categories</span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.25 }}
            className="text-white/65 text-body-lg max-w-2xl mx-auto mb-10">
            Not all waste is created equal. Explore 12 major waste categories — each with unique characteristics, handling requirements, and recycling pathways.
          </motion.p>

          {/* Search bar */}
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.4 }}
            className="relative max-w-lg mx-auto">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-white/40" />
            <input
              type="text"
              placeholder="Search waste categories..."
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full pl-12 pr-6 py-4 rounded-2xl text-white placeholder-white/40 outline-none"
              style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.15)', backdropFilter: 'blur(12px)' }}
            />
          </motion.div>
        </div>

        <div className="absolute bottom-0 left-0 right-0 h-24"
          style={{ background: 'linear-gradient(transparent, #050d1a)' }} />
      </section>

      {/* ─── FILTER TAGS + GRID ─── */}
      <section className="py-16 px-4" style={{ background: '#050d1a' }}>
        <div className="container-xl">

          {/* Filter pills */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.6 }}
            className="flex flex-wrap gap-2 justify-center mb-12">
            {tags.map(tag => (
              <motion.button key={tag}
                onClick={() => setFilter(tag)}
                whileHover={{ scale: 1.06 }} whileTap={{ scale: 0.96 }}
                className="px-4 py-1.5 rounded-full text-xs font-bold transition-all"
                style={{
                  background: filter === tag ? 'var(--green-primary)' : 'rgba(255,255,255,0.07)',
                  color: filter === tag ? 'white' : 'rgba(255,255,255,0.55)',
                  border: `1px solid ${filter === tag ? 'var(--green-primary)' : 'rgba(255,255,255,0.1)'}`,
                }}>
                {tag}
              </motion.button>
            ))}
          </motion.div>

          {/* Results count */}
          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }}
            className="text-white/30 text-sm text-center mb-8">
            Showing {filtered.length} of {categories.length} categories
          </motion.p>

          {/* Category grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {filtered.map((cat, i) => (
              <motion.div key={cat.slug}
                initial={{ opacity: 0, y: 40, scale: 0.9 }}
                whileInView={{ opacity: 1, y: 0, scale: 1 }}
                viewport={{ once: true, margin: '-40px' }}
                transition={{ duration: 0.5, delay: i * 0.06 }}
                whileHover={{ y: -8, scale: 1.02 }}
                className="group">
                <Link href={`/waste-categories/${cat.slug}`} className="block h-full">
                  <div className="h-full rounded-3xl p-6 relative overflow-hidden cursor-pointer transition-all duration-300"
                    style={{
                      background: cat.bgColor,
                      border: `1px solid ${cat.color}30`,
                      backdropFilter: 'blur(12px)',
                    }}>
                    {/* Top accent */}
                    <div className="absolute top-0 left-0 right-0 h-1 rounded-t-3xl"
                      style={{ background: cat.color }} />

                    {/* Glow on hover */}
                    <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-3xl"
                      style={{ background: `radial-gradient(ellipse at top, ${cat.color}15, transparent 60%)` }} />

                    <div className="relative z-10">
                      {/* Emoji + Tag */}
                      <div className="flex items-start justify-between mb-4">
                        <motion.div
                          animate={{ rotate: [0, 5, -5, 0] }}
                          transition={{ duration: 4, repeat: Infinity, delay: i * 0.2 }}
                          className="text-4xl">
                          {cat.emoji}
                        </motion.div>
                        <span className="text-[10px] font-bold uppercase tracking-widest px-2.5 py-1 rounded-full"
                          style={{ background: `${cat.tagColor}20`, color: cat.tagColor, border: `1px solid ${cat.tagColor}35` }}>
                          {cat.tag}
                        </span>
                      </div>

                      {/* Name */}
                      <h3 className="text-xl font-bold text-white mb-2 group-hover:text-[var(--green-primary)] transition-colors">
                        {cat.name}
                      </h3>

                      {/* Description */}
                      <p className="text-white/55 text-xs leading-relaxed mb-5">{cat.desc}</p>

                      {/* CTA */}
                      <div className="flex items-center gap-2 text-xs font-semibold transition-all"
                        style={{ color: cat.color }}>
                        Learn more
                        <motion.span className="group-hover:translate-x-1 transition-transform">
                          <ArrowRight className="w-3.5 h-3.5" />
                        </motion.span>
                      </div>
                    </div>
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>

          {/* Empty state */}
          {filtered.length === 0 && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
              className="text-center py-20">
              <div className="text-5xl mb-4">🔍</div>
              <p className="text-white/40 text-lg">No categories match your search</p>
              <button onClick={() => { setSearch(''); setFilter('All'); }}
                className="mt-4 btn-crystal btn-crystal-outline">
                Clear filters
              </button>
            </motion.div>
          )}
        </div>
      </section>

      {/* ─── INFO STRIP ─── */}
      <section className="py-16 px-4" style={{ background: '#0a1628' }}>
        <div className="container-xl">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {[
              { emoji: '♻️', stat: '12', label: 'Waste Category Types', color: '#00C47D' },
              { emoji: '🌍', stat: '2.24B', label: 'Tonnes Generated Yearly', color: '#EF4444' },
              { emoji: '🏭', stat: '19%', label: 'Global Recycling Rate', color: '#006FEF' },
              { emoji: '💡', stat: '5 R\'s', label: 'Prevention Principles', color: '#8B5CF6' },
            ].map((item, i) => (
              <motion.div key={i}
                initial={{ opacity: 0, scale: 0.85 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.1 }}
                className="text-center p-6 rounded-2xl"
                style={{ background: `${item.color}10`, border: `1px solid ${item.color}20` }}>
                <div className="text-3xl mb-2">{item.emoji}</div>
                <div className="text-2xl font-black mb-1" style={{ color: item.color }}>{item.stat}</div>
                <div className="text-white/45 text-xs">{item.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

    </main>
  );
}
