'use client';

import { motion } from 'framer-motion';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, CheckCircle, AlertTriangle, Recycle, MapPin, TrendingUp, Leaf, ShieldCheck } from 'lucide-react';

/* ══════════════════════════════════════════════════════════
   FULL CATEGORY DATA OBJECT (all 12 categories)
══════════════════════════════════════════════════════════ */
interface CategoryDetail {
  slug: string;
  emoji: string;
  name: string;
  color: string;
  bgGradient: string;
  tagline: string;
  overview: string;
  characteristics: string[];
  stats: { value: string; label: string }[];
  handling: { title: string; desc: string; icon: string }[];
  environmentalImpact: { positive?: string; negative: string; mitigation: string };
  facilities: { name: string; type: string; emoji: string }[];
  disposalSteps: string[];
  didYouKnow: string;
}

const categoriesData: Record<string, CategoryDetail> = {
  municipal: {
    slug: 'municipal', emoji: '🏠', name: 'Municipal Waste', color: '#F97316',
    bgGradient: 'linear-gradient(135deg, #1a0a05 0%, #0a1628 60%, #1a0a05 100%)',
    tagline: 'Household & Commercial Solid Waste',
    overview: 'Municipal solid waste (MSW) encompasses the everyday waste generated by households, businesses, schools, and institutions. It is the most familiar waste stream and includes food scraps, packaging, clothing, furniture, and general rubbish. In high-income countries, each person generates an average of 1.2 kg of MSW per day.',
    characteristics: ['Mix of organic, recyclable, and non-recyclable materials', 'Highly variable composition by region and income level', 'Collected regularly by municipal waste services', 'Managed through landfill, incineration, recycling, and composting'],
    stats: [
      { value: '2.24B', label: 'Tonnes generated globally per year' },
      { value: '46%', label: 'Could be composted or recycled' },
      { value: '37%', label: 'Currently sent to landfill' },
      { value: '1.2 kg', label: 'Generated per person per day (avg)' },
    ],
    handling: [
      { icon: '🗑️', title: 'Source Separation', desc: 'Separate organic waste, recyclables, and general waste at home using colour-coded bins. This is the single most impactful action.' },
      { icon: '♻️', title: 'Curbside Recycling', desc: 'Place clean, dry recyclables (paper, plastic, metal, glass) in your recycling bin on collection day.' },
      { icon: '🌱', title: 'Home Composting', desc: 'Compost food scraps and garden waste at home or use municipal green waste collection where available.' },
      { icon: '🏪', title: 'Special Drop-offs', desc: 'Take hazardous household items (batteries, paint, electronics) to designated drop-off facilities.' },
    ],
    environmentalImpact: {
      negative: 'Improper MSW disposal contributes to soil and water contamination, methane emissions from landfills (a potent greenhouse gas), litter, and disease vectors including rats and mosquitoes.',
      mitigation: 'Diverting organic waste from landfills alone can reduce municipal GHG contributions by up to 20%. Recycling and composting programs reduce extraction of virgin resources.',
    },
    facilities: [
      { name: 'Materials Recovery Facility (MRF)', type: 'Recycling Sort', emoji: '⚙️' },
      { name: 'Sanitary Landfill', type: 'Final Disposal', emoji: '🏔️' },
      { name: 'Waste-to-Energy Plant', type: 'Energy Recovery', emoji: '⚡' },
      { name: 'Composting Facility', type: 'Organic Diversion', emoji: '🌱' },
    ],
    disposalSteps: ['Separate waste at source into organic, recyclable, and general', 'Rinse recyclable containers before placing in bin', 'Compost eligible food scraps', 'Place bins at kerbside on scheduled collection day', 'Dispose of hazardous items at special facilities only'],
    didYouKnow: 'If all the food waste generated globally were a country, it would be the third largest greenhouse gas emitter — after China and the US.',
  },
  industrial: {
    slug: 'industrial', emoji: '🏭', name: 'Industrial Waste', color: '#64748B',
    bgGradient: 'linear-gradient(135deg, #0a0a1a 0%, #0a1628 60%, #0a0a1a 100%)',
    tagline: 'Manufacturing & Process Byproducts',
    overview: 'Industrial waste originates from manufacturing, mining, construction, and other industrial processes. It includes a wide range of materials from non-hazardous slag and fly ash to highly toxic chemical byproducts. Industrial waste often requires specialised treatment before disposal or recovery.',
    characteristics: ['Highly variable — depends on industry type', 'Can be liquid, solid, or gaseous', 'May contain hazardous constituents requiring special handling', 'Often generated in large volumes at concentrated point sources'],
    stats: [
      { value: '7.6B', label: 'Tonnes of industrial waste generated annually' },
      { value: '60%', label: 'Non-hazardous industrial waste reused or recovered' },
      { value: '$780B', label: 'Cost of industrial waste management globally' },
      { value: '40%', label: 'Of all toxic releases from manufacturing' },
    ],
    handling: [
      { icon: '📋', title: 'Waste Auditing', desc: 'Conduct regular waste audits to characterise and quantify waste streams — the first step to efficient management.' },
      { icon: '🔄', title: 'Industrial Symbiosis', desc: "Connect with nearby facilities to exchange waste materials — one industry's byproduct is another's raw material." },
      { icon: '⚗️', title: 'Waste Treatment', desc: 'Chemical, biological, or physical treatment of industrial effluents before discharge to water or land.' },
      { icon: '📜', title: 'Regulatory Compliance', desc: 'Maintain waste transfer notes, manifests, and licenses as required by environmental regulations.' },
    ],
    environmentalImpact: {
      negative: 'Industrial waste is responsible for significant soil and groundwater contamination, acid rain (from SO₂ emissions), heavy metal bioaccumulation in food chains, and air quality degradation.',
      mitigation: 'Industrial ecology and cleaner production technologies can reduce waste generation by up to 50% at source. Zero-waste manufacturing targets are achievable with circular design.',
    },
    facilities: [
      { name: 'Industrial Waste Treatment Plant', type: 'Treatment', emoji: '⚗️' },
      { name: 'Hazardous Waste Landfill', type: 'Containment', emoji: '🚫' },
      { name: 'Waste Exchange Network', type: 'Industrial Symbiosis', emoji: '🔄' },
      { name: 'Industrial Composting', type: 'Organic Recovery', emoji: '♻️' },
    ],
    disposalSteps: ['Characterise waste by type and hazardous classification', 'Engage a licensed waste carrier for collection', 'Complete waste transfer documentation', 'Send to licensed treatment or disposal facility', 'Maintain records for regulatory compliance'],
    didYouKnow: 'The Kalundborg Symbiosis in Denmark — the world\'s first industrial symbiosis park — exchanges 30 waste streams between 11 companies, saving $15 million annually.',
  },
  hazardous: {
    slug: 'hazardous', emoji: '⚠️', name: 'Hazardous Waste', color: '#EF4444',
    bgGradient: 'linear-gradient(135deg, #1a0505 0%, #0a1628 60%, #1a0505 100%)',
    tagline: 'Toxic, Flammable & Dangerous Materials',
    overview: 'Hazardous waste poses immediate or long-term risks to human health and the environment due to its toxic, flammable, corrosive, reactive, or infectious properties. It requires specialised handling, transport, treatment, and disposal under strict regulatory oversight.',
    characteristics: ['Toxic, flammable, corrosive, reactive, or infectious', 'Requires licensed waste carriers and facilities', 'Strictly regulated under national and international law', 'Can persist in the environment for decades or centuries'],
    stats: [
      { value: '400M', label: 'Tonnes of hazardous waste per year globally' },
      { value: '70%', label: 'Generated by industrial nations' },
      { value: '$50B+', label: 'Estimated illegal dumping cost annually' },
      { value: '100+', label: 'Years some toxins persist in soil' },
    ],
    handling: [
      { icon: '🧤', title: 'Personal Protection', desc: 'Always use appropriate PPE — gloves, eye protection, respirators — when handling hazardous materials.' },
      { icon: '🏷️', title: 'Proper Labelling', desc: 'Label all hazardous waste containers with content, hazard class, date, and generator information.' },
      { icon: '🚛', title: 'Licensed Transport', desc: 'Only licensed carriers may transport hazardous waste. Obtain required manifests before movement.' },
      { icon: '🔒', title: 'Secure Storage', desc: 'Store hazardous waste in secure, bunded areas away from drains, with incompatibles separated.' },
    ],
    environmentalImpact: {
      negative: 'Illegal dumping of hazardous waste causes irreversible soil and groundwater contamination. Exposure to dioxins, heavy metals, and persistent organic pollutants causes cancer, birth defects, and neurological damage.',
      mitigation: 'Strict regulation, improved industrial processes, substitution of toxic chemicals, and extended producer responsibility are the most effective mitigation strategies.',
    },
    facilities: [
      { name: 'Secure Hazardous Waste Landfill', type: 'Containment', emoji: '🔒' },
      { name: 'High-Temperature Incinerator', type: 'Thermal Treatment', emoji: '🔥' },
      { name: 'Chemical Treatment Facility', type: 'Neutralisation', emoji: '⚗️' },
      { name: 'Deep Well Injection Site', type: 'Disposal', emoji: '🕳️' },
    ],
    disposalSteps: ['Never mix hazardous with general waste', 'Store in original containers where possible', 'Engage a licensed hazardous waste contractor', 'Complete consignment notes and manifests', 'Retain copies of all disposal documentation for 3+ years'],
    didYouKnow: 'The Love Canal disaster (1978) in New York — where 21,000 tonnes of chemical waste beneath a housing estate caused widespread illness — led directly to the creation of the US Superfund law.',
  },
  medical: {
    slug: 'medical', emoji: '🏥', name: 'Medical Waste', color: '#EC4899',
    bgGradient: 'linear-gradient(135deg, #1a0510 0%, #0a1628 60%, #1a0510 100%)',
    tagline: 'Healthcare & Biohazardous Waste',
    overview: 'Medical waste — also called healthcare or clinical waste — includes all waste generated by healthcare facilities: hospitals, clinics, dental practices, laboratories, and veterinary services. It encompasses sharps, infectious materials, pharmaceuticals, and anatomical waste, all requiring careful management to prevent disease transmission.',
    characteristics: ['Includes sharps, infectious, pharmaceutical, and radioactive waste', 'High infection and injury risk if improperly handled', 'Strictly regulated under healthcare waste management regulations', 'Small volume but disproportionately high risk'],
    stats: [
      { value: '5.9M', label: 'Tonnes of healthcare waste annually' },
      { value: '85%', label: 'Is non-hazardous general waste' },
      { value: '15%', label: 'Is hazardous/infectious material', },
      { value: '16B', label: 'Injections given annually — safe disposal critical' },
    ],
    handling: [
      { icon: '🟡', title: 'Yellow Bag (Clinical)', desc: 'Infectious and anatomical waste goes in yellow bags for high-temperature incineration.' },
      { icon: '🟠', title: 'Orange Bag (Offensive)', desc: 'Non-infectious hygiene waste goes in orange bags and may be landfilled after appropriate treatment.' },
      { icon: '🔴', title: 'Sharps Container', desc: 'All needles, blades, and sharps must be placed in rigid puncture-proof yellow sharps bins immediately after use.' },
      { icon: '💊', title: 'Pharmaceutical Disposal', desc: 'Expired or unused medications must never go in general waste. Return to pharmacy or use dedicated disposal containers.' },
    ],
    environmentalImpact: {
      negative: 'Open burning of medical waste releases dioxins and furans — among the most toxic compounds known. Improper disposal spreads bloodborne pathogens including HIV and Hepatitis B/C.',
      mitigation: 'Autoclave sterilisation before landfill, high-temperature incineration with scrubbers, and pharmaceutical take-back programs significantly reduce risk.',
    },
    facilities: [
      { name: 'Clinical Waste Incinerator', type: 'Thermal Treatment', emoji: '🔥' },
      { name: 'Autoclave Facility', type: 'Sterilisation', emoji: '♨️' },
      { name: 'Pharmaceutical Return Point', type: 'Drug Disposal', emoji: '💊' },
      { name: 'Sharps Disposal Service', type: 'Needle Safety', emoji: '🔴' },
    ],
    disposalSteps: ['Segregate waste at point of generation into correct streams', 'Never re-cap needles — place directly in sharps container', 'Seal and label containers before removal from clinical areas', 'Only licensed healthcare waste contractors may collect', 'Ensure treatment certificates are retained'],
    didYouKnow: 'In 2020, the COVID-19 pandemic generated an estimated 140 million test kits and 731,000 litres of chemical waste — highlighting the urgent need for emergency medical waste protocols.',
  },
  construction: {
    slug: 'construction', emoji: '🏗️', name: 'Construction Waste', color: '#A78BFA',
    bgGradient: 'linear-gradient(135deg, #0a0515 0%, #0a1628 60%, #0a0515 100%)',
    tagline: 'Demolition & Building Debris',
    overview: 'Construction and demolition (C&D) waste is generated during the building, renovation, and demolition of structures. It is one of the largest waste streams by volume, comprising concrete, timber, metals, bricks, glass, and plasterboard. Much of it is inert and recyclable, yet globally less than half is diverted from landfill.',
    characteristics: ['Largest waste stream by volume in many countries', 'Predominantly inert materials: concrete, bricks, asphalt', 'Mixed with hazardous materials in older buildings (asbestos, lead paint)', 'Highly recyclable if separated at source on site'],
    stats: [
      { value: '3B', label: 'Tonnes of C&D waste generated annually' },
      { value: '40%', label: 'Of all landfill waste in some regions' },
      { value: '90%', label: 'Could be recycled with on-site sorting' },
      { value: '75%', label: 'EU C&D waste recovery rate (target)' },
    ],
    handling: [
      { icon: '📋', title: 'Site Waste Management Plan', desc: 'Prepare a waste management plan before work begins — estimate waste volumes and identify disposal routes.' },
      { icon: '🔨', title: 'Selective Demolition', desc: 'Deconstruct rather than demolish — carefully remove valuable materials for reuse before bringing in machinery.' },
      { icon: '🗂️', title: 'On-Site Segregation', desc: 'Separate concrete, timber, metal, and plasterboard into dedicated skips on site to maximise recovery value.' },
      { icon: '🏚️', title: 'Asbestos Survey', desc: 'Always conduct an asbestos survey before demolition of buildings built before 2000. Licensed removal is mandatory.' },
    ],
    environmentalImpact: {
      negative: 'C&D waste in landfill wastes valuable secondary materials, produces leachate, and takes up vast space. Asbestos, lead, and PCBs in demolition debris are serious long-term health hazards.',
      mitigation: 'Selective deconstruction, on-site material recovery, and use of recycled aggregates in new construction can divert over 90% of C&D waste from landfill.',
    },
    facilities: [
      { name: 'Inert Waste Landfill', type: 'Final Disposal', emoji: '🏔️' },
      { name: 'Aggregate Recycling Plant', type: 'Concrete Crushing', emoji: '⚙️' },
      { name: 'Timber Recovery Centre', type: 'Wood Recycling', emoji: '🌲' },
      { name: 'Metal Scrap Yard', type: 'Metal Recovery', emoji: '🔩' },
    ],
    disposalSteps: ['Complete pre-demolition asbestos and hazardous materials survey', 'Prepare site waste management plan', 'Set up on-site segregation skips', 'Engage licensed contractors for hazardous material removal', 'Send segregated materials to appropriate recycling facilities'],
    didYouKnow: 'Recycled concrete aggregate (RCA) can replace up to 30% of virgin aggregate in new construction without compromising structural strength — saving quarrying and transportation energy.',
  },
  agricultural: {
    slug: 'agricultural', emoji: '🌾', name: 'Agricultural Waste', color: '#84CC16',
    bgGradient: 'linear-gradient(135deg, #051505 0%, #0a1628 60%, #051505 100%)',
    tagline: 'Farm & Crop Residues',
    overview: 'Agricultural waste includes all materials generated in the process of food and fibre production — from crop residues and animal manure to agrochemical containers and plastic mulch film. When managed well, much agricultural waste is a valuable resource; when mismanaged, it becomes a significant pollutant.',
    characteristics: ['Seasonally variable — follows crop cycles', 'Large volumes of organic material (crop residues, manure)', 'Chemical hazards from pesticide and fertiliser containers', 'Often managed on-site at farm level'],
    stats: [
      { value: '5B', label: 'Tonnes of crop residue generated annually' },
      { value: '70%', label: 'Of agricultural waste is organic/biodegradable' },
      { value: '200M', label: 'Tonnes of animal manure produced daily' },
      { value: '75%', label: 'Of global freshwater used in agriculture' },
    ],
    handling: [
      { icon: '🌱', title: 'Composting', desc: 'Compost crop residues and manure into nutrient-rich organic fertiliser — returning value to the soil.' },
      { icon: '⚡', title: 'Biogas Generation', desc: 'Anaerobic digestion of manure and organic waste produces biogas for energy and digestate for fertiliser.' },
      { icon: '🔥', title: 'Crop Residue Management', desc: 'Incorporate residues into soil rather than burning — burning releases CO₂, particulates, and destroys soil structure.' },
      { icon: '🧴', title: 'Container Management', desc: 'Triple-rinse pesticide containers, pierce them, and return to licensed collection schemes. Never burn.' },
    ],
    environmentalImpact: {
      negative: 'Crop burning pollutes air quality and releases CO₂. Manure runoff causes eutrophication — oxygen depletion in waterways. Pesticide containers contaminate soil and groundwater when improperly discarded.',
      mitigation: 'No-burn policies, biogas plants, constructed wetlands for runoff treatment, and container return schemes can dramatically reduce agricultural waste pollution.',
    },
    facilities: [
      { name: 'Agricultural Composting Facility', type: 'Organic Recovery', emoji: '🌱' },
      { name: 'Anaerobic Digester', type: 'Biogas Plant', emoji: '⚡' },
      { name: 'Agrochemical Container Return', type: 'Chemical Disposal', emoji: '🧴' },
      { name: 'Farm Waste Contractor', type: 'Collection Service', emoji: '🚜' },
    ],
    disposalSteps: ['Compost organic residues on-site where possible', 'Return agrochemical containers through licensed schemes', 'Manage manure through anaerobic digestion or composting', 'Avoid open burning of crop residues', 'Dispose of veterinary medicines through pharmacy return'],
    didYouKnow: 'If managed as biogas instead of being left to decompose openly, global livestock manure could produce enough energy to power 100 million homes.',
  },
  organic: {
    slug: 'organic', emoji: '🍃', name: 'Organic Waste', color: '#00C47D',
    bgGradient: 'linear-gradient(135deg, #011a0a 0%, #0a1628 60%, #011a0e 100%)',
    tagline: 'Biodegradable Food & Yard Waste',
    overview: 'Organic waste — food scraps, garden clippings, and other biodegradable materials — accounts for roughly 44% of all municipal solid waste globally. When diverted from landfill and composted or anaerobically digested, it transforms into valuable soil amendment and energy, closing the nutrient cycle.',
    characteristics: ['Food scraps, garden waste, paper, wood', 'Rapidly biodegradable', 'Produces methane in landfill (potent GHG)', 'Highly valuable when composted or digested'],
    stats: [
      { value: '44%', label: 'Of MSW is organic/biodegradable' },
      { value: '1.3B', label: 'Tonnes of food wasted annually' },
      { value: '8%', label: 'Of global GHGs from food waste' },
      { value: '30%', label: 'Reduction in home waste through composting' },
    ],
    handling: [
      { icon: '🪣', title: 'Kitchen Caddy', desc: 'Collect food scraps in a small kitchen caddy. Line with compostable bags and empty regularly into outdoor bin.' },
      { icon: '🌿', title: 'Home Composting', desc: 'A backyard compost bin turns food and garden waste into rich compost in 6–12 weeks. Great for gardens.' },
      { icon: '🍂', title: 'Green Waste Collection', desc: 'Many councils collect garden waste separately for large-scale composting. Use the service to divert waste from landfill.' },
      { icon: '⚡', title: 'Anaerobic Digestion', desc: 'Food waste anaerobically digested produces biogas (electricity and heat) and digestate (liquid fertiliser).' },
    ],
    environmentalImpact: {
      positive: 'Composted organic waste improves soil structure, water retention, and fertility — reducing the need for synthetic fertilisers and their associated emissions.',
      negative: 'Organic waste in landfill decomposes anaerobically, producing methane — a greenhouse gas 28× more potent than CO₂ over 100 years.',
      mitigation: 'Home composting, food waste reduction, separate organic collection, and anaerobic digestion are the most effective interventions.',
    },
    facilities: [
      { name: 'In-Vessel Composting Plant', type: 'Composting', emoji: '🌱' },
      { name: 'Anaerobic Digestion Facility', type: 'Biogas & Fertiliser', emoji: '⚡' },
      { name: 'Community Composting Site', type: 'Local Recovery', emoji: '🤝' },
      { name: 'Landfill with Gas Capture', type: 'Energy Recovery', emoji: '🔥' },
    ],
    disposalSteps: ['Compost at home if space allows', 'Use a kitchen caddy for food scraps', 'Place green waste in council collection bin', 'Avoid contaminating food waste with non-compostables', 'Reduce food waste through meal planning and storage'],
    didYouKnow: 'One tonne of food waste composted prevents 0.7 tonnes of CO₂-equivalent emissions versus landfill — while producing 300 kg of compost worth ~$60 as a soil amendment.',
  },
  electronic: {
    slug: 'electronic', emoji: '💻', name: 'Electronic Waste', color: '#006FEF',
    bgGradient: 'linear-gradient(135deg, #010a1a 0%, #0a1628 60%, #010a1a 100%)',
    tagline: 'E-Waste & Discarded Electronics',
    overview: 'Electronic waste (e-waste) is the fastest-growing waste stream globally, generated by discarded computers, smartphones, TVs, appliances, and other electronic equipment. It contains both valuable recoverable materials (gold, silver, copper) and toxic substances (lead, mercury, cadmium) that cause severe harm when improperly processed.',
    characteristics: ['Fastest-growing waste stream globally', 'Contains toxic: lead, mercury, cadmium, flame retardants', 'Contains valuable: gold, silver, copper, rare earth metals', 'Only 17.4% formally recycled in 2021'],
    stats: [
      { value: '57.4M', label: 'Tonnes of e-waste generated in 2021' },
      { value: '17.4%', label: 'Formally recycled and documented' },
      { value: '$57B', label: 'Worth of raw materials discarded in e-waste' },
      { value: '82%', label: 'Increase in e-waste generation since 2010' },
    ],
    handling: [
      { icon: '🔧', title: 'Repair First', desc: 'Before replacing, check if your device can be repaired. Many electronics fail due to a single replaceable component.' },
      { icon: '🔄', title: 'Manufacturer Take-Back', desc: 'Many manufacturers (Apple, Samsung, Dell) offer trade-in and recycling programs for old devices.' },
      { icon: '🏪', title: 'Certified Recyclers', desc: 'Use e-Stewards or R2-certified e-waste recyclers who ensure responsible processing and data destruction.' },
      { icon: '🎁', title: 'Donate & Reuse', desc: 'Working devices can be donated to schools, charities, or refurbishment organisations for a second life.' },
    ],
    environmentalImpact: {
      negative: 'Informal e-waste processing — open burning and acid baths — releases neurotoxins into air, soil, and water. Children in informal processing communities show 5× higher blood lead levels.',
      mitigation: 'Extended producer responsibility laws, take-back programs, and right-to-repair legislation are the most effective policy tools to address e-waste.',
    },
    facilities: [
      { name: 'Certified E-Waste Recycler', type: 'Formal Recycling', emoji: '♻️' },
      { name: 'Manufacturer Take-Back Point', type: 'Producer Responsibility', emoji: '📱' },
      { name: 'Refurbishment Centre', type: 'Device Reuse', emoji: '🔧' },
      { name: 'Precious Metal Recovery Plant', type: 'Urban Mining', emoji: '⛏️' },
    ],
    disposalSteps: ['Data wipe all devices before disposal', 'Check manufacturer take-back or trade-in programs', 'Find your nearest certified e-waste collection point', 'Never place electronics in general waste bins', 'Remove batteries and dispose of separately'],
    didYouKnow: 'One tonne of e-waste contains 100× more gold than one tonne of gold ore. Urban mining of e-waste is increasingly more economical than conventional mining.',
  },
  plastic: {
    slug: 'plastic', emoji: '🧴', name: 'Plastic Waste', color: '#00B8D9',
    bgGradient: 'linear-gradient(135deg, #01101a 0%, #0a1628 60%, #01101a 100%)',
    tagline: 'Polymer-Based Packaging & Products',
    overview: 'Plastic waste encompasses all discarded polymer-based materials — from single-use packaging to complex multi-material composites. With over 400 million tonnes produced annually and less than 9% ever recycled in history, plastic pollution is one of the defining environmental challenges of our era.',
    characteristics: ['7 major resin types (PET, HDPE, PVC, LDPE, PP, PS, Other)', 'Persists for 400–1000 years in the environment', 'Breaks into microplastics — found in food, water, human blood', 'Highly variable recyclability depending on resin and colour'],
    stats: [
      { value: '400M', label: 'Tonnes of plastic produced annually' },
      { value: '9%', label: 'Of all plastic ever produced recycled' },
      { value: '8M', label: 'Tonnes enter the ocean each year' },
      { value: '2050', label: 'Year oceans may contain more plastic than fish (by weight)' },
    ],
    handling: [
      { icon: '🔢', title: 'Check the Resin Code', desc: 'Look for the ♻ symbol with a number 1–7. #1 (PET) and #2 (HDPE) are most widely recycled.' },
      { icon: '🚰', title: 'Rinse Containers', desc: 'Rinse plastic containers to remove food residue before recycling. Contamination is the top reason for rejection.' },
      { icon: '❌', title: 'Know What\'s Not Recyclable', desc: 'Black plastic, cling film, and multi-layer packaging are generally not recyclable in standard systems.' },
      { icon: '🛒', title: 'Plastic Film Drop-Off', desc: 'Soft plastics (bags, film) cannot go in kerbside recycling — return to dedicated supermarket collection points.' },
    ],
    environmentalImpact: {
      negative: 'Plastic pollution kills over 1 million seabirds and 100,000 marine mammals annually. Microplastics have been found in the deepest ocean trenches and the highest mountain peaks.',
      mitigation: 'A combination of reduction, design for recyclability, extended producer responsibility, and investment in recycling infrastructure can address the plastic crisis.',
    },
    facilities: [
      { name: 'Plastic MRF', type: 'Sorting Facility', emoji: '⚙️' },
      { name: 'Pelletising Plant', type: 'Reprocessing', emoji: '🔬' },
      { name: 'Soft Plastic Collection', type: 'Film Recycling', emoji: '🛍️' },
      { name: 'Chemical Recycling Plant', type: 'Advanced Processing', emoji: '⚗️' },
    ],
    disposalSteps: ['Check resin codes — prioritise #1 and #2 plastics', 'Rinse all containers before recycling', 'Remove lids and caps (check local rules)', 'Return soft plastics to supermarket collection points', 'Reduce single-use plastic consumption at source'],
    didYouKnow: 'A single plastic bag can take 20 years to decompose; a plastic bottle, 450 years. In that time, it fragments into microplastics that enter food chains indefinitely.',
  },
  paper: {
    slug: 'paper', emoji: '📄', name: 'Paper Waste', color: '#EAB308',
    bgGradient: 'linear-gradient(135deg, #1a1005 0%, #0a1628 60%, #1a1005 100%)',
    tagline: 'Cellulose-Based Recyclable Waste',
    overview: 'Paper and cardboard waste is one of the most widely recycled materials globally, yet still represents a significant portion of landfill. Made from cellulose fibres, paper can be recycled 5–7 times before fibres become too short. Recycling paper saves trees, water, and energy compared to virgin production.',
    characteristics: ['Cellulose fibres recyclable up to 7 times', 'Biodegradable but takes years in landfill', 'Wide variety: newsprint, cardboard, office paper, packaging', 'Contamination by food, moisture, or wax destroys recyclability'],
    stats: [
      { value: '400M', label: 'Tonnes of paper produced annually' },
      { value: '58%', label: 'Global paper recycling rate' },
      { value: '17', label: 'Trees saved per tonne recycled' },
      { value: '7,000', label: 'Gallons of water saved per tonne recycled' },
    ],
    handling: [
      { icon: '📦', title: 'Flatten Cardboard', desc: 'Flatten cardboard boxes to save space in collection vehicles. Remove plastic tape and polystyrene inserts.' },
      { icon: '🍕', title: 'No Greasy Pizza Boxes', desc: 'Food-contaminated cardboard cannot be recycled. Tear off the clean top and recycle it; compost the greasy base.' },
      { icon: '🗞️', title: 'Loose Paper', desc: 'Loose paper and junk mail can go directly in the recycling bin. Shredded paper should be bagged separately.' },
      { icon: '☕', title: 'Coffee Cups Are NOT Paper', desc: 'Disposable coffee cups have a plastic lining — they cannot go in paper recycling. Use a reusable cup.' },
    ],
    environmentalImpact: {
      negative: 'Paper production is responsible for 10% of global industrial water withdrawals, significant forest clearing, and bleaching chemicals. Landfilled paper produces methane as it decomposes anaerobically.',
      mitigation: 'Paper recycling and FSC-certified virgin paper dramatically reduce impact. Going paperless eliminates it entirely.',
    },
    facilities: [
      { name: 'Paper Mill (Recycled)', type: 'Pulp Processing', emoji: '🏭' },
      { name: 'Cardboard Baling Centre', type: 'Pre-processing', emoji: '📦' },
      { name: 'Shredded Paper Facility', type: 'Secure Destruction', emoji: '🔒' },
      { name: 'Office Paper Recycling', type: 'Commercial Collection', emoji: '🏢' },
    ],
    disposalSteps: ['Remove plastic windows from envelopes before recycling', 'Flatten and bundle cardboard', 'Keep paper dry — wet paper cannot be recycled', 'Compost food-contaminated paper', 'Shred confidential documents before recycling'],
    didYouKnow: 'Recycling one tonne of paper saves 4,000 kWh of electricity — enough to power the average home for 5 months. Paper fibres can be recycled up to 7 times before they become too short.',
  },
  glass: {
    slug: 'glass', emoji: '🪟', name: 'Glass Waste', color: '#22D3EE',
    bgGradient: 'linear-gradient(135deg, #01151a 0%, #0a1628 60%, #01151a 100%)',
    tagline: 'Silica-Based Infinitely Recyclable Material',
    overview: 'Glass is one of the most sustainable packaging materials — made primarily from silica (sand) and 100% recyclable indefinitely without loss of quality or purity. Recycled glass (cullet) reduces the energy needed in glass manufacturing and extends furnace life. Despite these benefits, glass is often landfilled due to collection logistics.',
    characteristics: ['100% recyclable with no quality degradation', 'Heavy — costly to transport for collection', 'Must be colour-sorted for highest quality recycling', 'Cannot be recycled with Pyrex, windows, or ceramics in standard systems'],
    stats: [
      { value: '100%', label: 'Recyclable without quality loss' },
      { value: '30%', label: 'Energy saved using cullet vs. raw materials' },
      { value: '20%', label: 'CO₂ reduction per 10% cullet in furnace' },
      { value: '1M', label: 'Years glass takes to decompose in landfill' },
    ],
    handling: [
      { icon: '🟢', title: 'Colour Sort', desc: 'Separate clear, green, and brown glass where required by local services — colour mixing reduces cullet quality.' },
      { icon: '🫙', title: 'Remove Lids', desc: 'Remove metal lids and plastic caps from glass jars before recycling (recycle lids separately with metals).' },
      { icon: '♻️', title: 'Bottle Banks', desc: 'Use designated glass bottle banks where kerbside glass collection is not available.' },
      { icon: '⚠️', title: 'What Cannot Be Recycled', desc: 'Pyrex, Ceramics, Window glass (float glass), and mirrors cannot go in standard glass recycling — they melt at different temperatures.' },
    ],
    environmentalImpact: {
      negative: 'Glass production is energy-intensive, using high temperatures (1,600°C) from fossil fuels. Glass in landfill occupies space indefinitely and can cause litter and injury hazards.',
      mitigation: 'Using cullet in glass production reduces furnace temperature needs. Each 10% of cullet substituted saves ~2.5% energy — making collection and colour sorting economically worthwhile.',
    },
    facilities: [
      { name: 'Glass Recycling MRF', type: 'Sorting & Crushing', emoji: '⚙️' },
      { name: 'Glass Furnace (Recycled)', type: 'Cullet Melting', emoji: '🔥' },
      { name: 'Aggregate Producer', type: 'Road/Construction Use', emoji: '🏗️' },
      { name: 'Bottle Bank Network', title: 'Drop-Off Collection', emoji: '🫙' } as any,
    ],
    disposalSteps: ['Rinse glass containers', 'Remove lids and labels where possible', 'Sort by colour if required locally', 'Do not include ceramics, Pyrex, or window glass', 'Take to bottle bank or kerbside glass bin'],
    didYouKnow: 'A recycled glass bottle saves enough energy to light a 100W bulb for 4 hours. Glass can be recycled from bottle to new bottle in as little as 30 days.',
  },
  metal: {
    slug: 'metal', emoji: '🔩', name: 'Metal Waste', color: '#8B5CF6',
    bgGradient: 'linear-gradient(135deg, #0a0515 0%, #0a1628 60%, #0a0515 100%)',
    tagline: 'Ferrous & Non-Ferrous Scrap Metal',
    overview: 'Metal waste — from aluminium cans to steel beams — is among the most valuable recyclable materials due to the enormous energy savings recycling affords over virgin production. Metals can be recycled infinitely without degradation, making them the cornerstone of the circular economy.',
    characteristics: ['Ferrous (iron, steel) and non-ferrous (aluminium, copper, precious metals)', 'Infinitely recyclable with no quality loss', 'Easily separated using magnets and eddy currents', 'High economic value — recovered through scrap trade globally'],
    stats: [
      { value: '95%', label: 'Energy saved recycling aluminium vs. virgin' },
      { value: '74%', label: 'Energy saved recycling steel vs. virgin' },
      { value: '∞', label: 'Times metals can be recycled', },
      { value: '60 days', label: 'Time for a can to return as a new can' },
    ],
    handling: [
      { icon: '🥤', title: 'Rinse Cans', desc: 'Rinse aluminium and steel cans to remove food. Crushing saves collection space but is not required.' },
      { icon: '🧲', title: 'The Magnet Test', desc: 'Ferrous metals attract magnets; aluminium and copper do not. Helps identify and separate different metals.' },
      { icon: '⛏️', title: 'Scrap Metal Yards', desc: 'Larger metal items (appliances, car parts, structural steel) can be taken to scrap metal yards for value.' },
      { icon: '🏠', title: 'Aerosol Cans', desc: 'Fully empty aerosol cans are recyclable as steel. Never puncture them — leave the nozzle on and ensure completely empty.' },
    ],
    environmentalImpact: {
      negative: 'Mining virgin metals causes massive habitat destruction, water contamination (acid mine drainage), and enormous energy consumption. Steel production alone accounts for 8% of global CO₂ emissions.',
      mitigation: 'Metal recycling is one of the most impactful environmental actions — each recycled tonne of aluminium saves 9 tonnes of CO₂-equivalent emissions versus virgin production.',
    },
    facilities: [
      { name: 'Scrap Metal Yard', type: 'Collection & Sorting', emoji: '⛏️' },
      { name: 'Steel Recycling Furnace', type: 'Reprocessing', emoji: '🔥' },
      { name: 'Aluminium Smelter', type: 'Non-Ferrous Recovery', emoji: '⚡' },
      { name: 'Precious Metal Refinery', type: 'High-Value Recovery', emoji: '✨' },
    ],
    disposalSteps: ['Rinse all food/drink cans before recycling', 'Place in kerbside recycling bin (check local rules)', 'Take large metal items to a scrap metal yard', 'Remove and separate non-metal components where possible', 'Never landfill metal — it has significant scrap value'],
    didYouKnow: 'Recycling one aluminium can saves enough energy to run a television for 3 hours. The aluminium industry saves $800 million in energy costs annually through recycling.',
  },
};

/* ══════════════════════════════════════
   PAGE COMPONENT
══════════════════════════════════════ */
export default function CategoryDetailPage({ params }: { params: { slug: string } }) {
  const cat = categoriesData[params.slug];
  if (!cat) notFound();

  return (
    <main className="overflow-x-hidden">

      {/* ─── HERO ─── */}
      <section className="relative min-h-[60vh] flex items-center overflow-hidden"
        style={{ background: cat.bgGradient }}>
        {/* Orbs */}
        <div className="absolute w-[600px] h-[600px] rounded-full -top-32 -left-32 pointer-events-none"
          style={{ background: `radial-gradient(circle, ${cat.color}25, transparent 65%)`, filter: 'blur(60px)' }} />
        <div className="absolute w-[400px] h-[400px] rounded-full -bottom-20 right-0 pointer-events-none"
          style={{ background: `radial-gradient(circle, ${cat.color}15, transparent 65%)`, filter: 'blur(60px)' }} />

        {/* Grid */}
        <div className="absolute inset-0 opacity-[0.04]"
          style={{ backgroundImage: `linear-gradient(${cat.color} 1px, transparent 1px), linear-gradient(90deg, ${cat.color} 1px, transparent 1px)`, backgroundSize: '60px 60px' }} />

        <div className="container-xl relative z-10 pt-28 pb-16">
          {/* Back button */}
          <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.5 }}>
            <Link href="/waste-categories"
              className="inline-flex items-center gap-2 mb-8 text-white/60 hover:text-white transition-colors text-sm font-medium">
              <ArrowLeft className="w-4 h-4" /> Back to All Categories
            </Link>
          </motion.div>

          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>
              {/* Emoji */}
              <motion.div
                animate={{ y: [0, -12, 0], rotate: [0, 5, -5, 0] }}
                transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
                className="text-7xl mb-6 inline-block">
                {cat.emoji}
              </motion.div>

              {/* Tag */}
              <div className="label-tag mb-4 w-fit"
                style={{ background: `${cat.color}15`, color: cat.color, border: `1px solid ${cat.color}35` }}>
                <Recycle className="w-3.5 h-3.5" /> Waste Category
              </div>

              <h1 className="heading-xl text-white mb-3">{cat.name}</h1>
              <p className="text-lg font-semibold mb-5" style={{ color: cat.color }}>{cat.tagline}</p>
              <p className="text-white/60 text-base leading-relaxed">{cat.overview}</p>
            </motion.div>

            {/* Stats grid */}
            <motion.div initial={{ opacity: 0, x: 50 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8, delay: 0.2 }}
              className="grid grid-cols-2 gap-4">
              {cat.stats.map((stat, i) => (
                <motion.div key={i}
                  initial={{ opacity: 0, scale: 0.85 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.3 + i * 0.1 }}
                  whileHover={{ scale: 1.05 }}
                  className="p-5 rounded-2xl text-center"
                  style={{ background: `${cat.color}12`, border: `1px solid ${cat.color}30` }}>
                  <div className="text-2xl font-black mb-1" style={{ color: cat.color }}>{stat.value}</div>
                  <div className="text-white/50 text-xs leading-tight">{stat.label}</div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── CHARACTERISTICS ─── */}
      <section className="py-16 px-4" style={{ background: '#050d1a' }}>
        <div className="container-lg">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.7 }}
            className="grid md:grid-cols-2 gap-12 items-start">
            <div>
              <div className="label-tag mb-4 w-fit border-white/20 text-white/70 bg-white/10">
                <ShieldCheck className="w-4 h-4" /> Key Characteristics
              </div>
              <h2 className="heading-lg text-white mb-6">What Defines <span style={{ color: cat.color }}>{cat.name}?</span></h2>
              <div className="space-y-3">
                {cat.characteristics.map((ch, i) => (
                  <motion.div key={i}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="flex items-start gap-3 p-4 rounded-xl"
                    style={{ background: `${cat.color}10`, border: `1px solid ${cat.color}20` }}>
                    <CheckCircle className="w-5 h-5 flex-shrink-0 mt-0.5" style={{ color: cat.color }} />
                    <span className="text-white/65 text-sm leading-relaxed">{ch}</span>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Did you know */}
            <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.2 }}
              className="p-8 rounded-3xl relative overflow-hidden"
              style={{ background: `${cat.color}12`, border: `2px solid ${cat.color}30` }}>
              <div className="text-4xl mb-4">💡</div>
              <h3 className="text-white font-bold text-lg mb-3">Did You Know?</h3>
              <p className="text-white/65 text-sm leading-relaxed">{cat.didYouKnow}</p>
              <div className="absolute bottom-0 right-0 text-9xl opacity-5 pointer-events-none select-none">
                {cat.emoji}
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ─── HOW TO HANDLE ─── */}
      <section className="py-16 px-4" style={{ background: '#0a1628' }}>
        <div className="container-xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.7 }}
            className="text-center mb-12">
            <div className="label-tag mx-auto mb-4 w-fit border-white/20 text-white/70 bg-white/10">
              <Recycle className="w-4 h-4" /> Disposal Guide
            </div>
            <h2 className="heading-lg text-white mb-2">How to Handle <span style={{ color: cat.color }}>{cat.name}</span></h2>
            <p className="text-white/45 text-sm">Step-by-step disposal and recycling guidance</p>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
            {cat.handling.map((h, i) => (
              <motion.div key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -6 }}
                className="p-6 rounded-2xl"
                style={{ background: 'rgba(255,255,255,0.04)', border: `1px solid ${cat.color}25` }}>
                <div className="text-3xl mb-4">{h.icon}</div>
                <h4 className="font-bold text-white text-sm mb-2">{h.title}</h4>
                <p className="text-white/50 text-xs leading-relaxed">{h.desc}</p>
              </motion.div>
            ))}
          </div>

          {/* Disposal steps */}
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.7 }}
            className="p-8 rounded-3xl"
            style={{ background: 'rgba(255,255,255,0.03)', border: `1px solid ${cat.color}25` }}>
            <h3 className="text-white font-bold text-lg mb-6 flex items-center gap-2">
              <span style={{ color: cat.color }}>→</span> Step-by-Step Disposal
            </h3>
            <div className="space-y-3">
              {cat.disposalSteps.map((step, si) => (
                <motion.div key={si}
                  initial={{ opacity: 0, x: -20 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: si * 0.08 }}
                  className="flex items-center gap-4">
                  <div className="w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-black"
                    style={{ background: `${cat.color}25`, color: cat.color }}>
                    {si + 1}
                  </div>
                  <span className="text-white/65 text-sm">{step}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>
        </div>
      </section>

      {/* ─── ENVIRONMENTAL IMPACT ─── */}
      <section className="py-16 px-4" style={{ background: '#050d1a' }}>
        <div className="container-lg">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.7 }}
            className="text-center mb-10">
            <div className="label-tag mx-auto mb-4 w-fit border-white/20 text-white/70 bg-white/10">
              <Leaf className="w-4 h-4" /> Environmental Impact
            </div>
            <h2 className="heading-lg text-white mb-2">Impact on Our Planet</h2>
          </motion.div>

          <div className="grid md:grid-cols-2 gap-6">
            {/* Negative */}
            <motion.div initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7 }}
              className="p-6 rounded-2xl"
              style={{ background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.2)' }}>
              <div className="flex items-center gap-3 mb-4">
                <AlertTriangle className="w-5 h-5 text-red-400" />
                <h3 className="text-red-400 font-bold">When Mismanaged</h3>
              </div>
              <p className="text-white/60 text-sm leading-relaxed">{cat.environmentalImpact.negative}</p>
            </motion.div>

            {/* Mitigation / Positive */}
            <motion.div initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.7, delay: 0.1 }}
              className="p-6 rounded-2xl"
              style={{ background: `${cat.color}08`, border: `1px solid ${cat.color}25` }}>
              <div className="flex items-center gap-3 mb-4">
                <TrendingUp className="w-5 h-5" style={{ color: cat.color }} />
                <h3 className="font-bold" style={{ color: cat.color }}>Mitigation Strategies</h3>
              </div>
              {cat.environmentalImpact.positive && (
                <p className="text-white/60 text-sm leading-relaxed mb-3">{cat.environmentalImpact.positive}</p>
              )}
              <p className="text-white/60 text-sm leading-relaxed">{cat.environmentalImpact.mitigation}</p>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ─── RELATED FACILITIES ─── */}
      <section className="py-16 px-4" style={{ background: '#0a1628' }}>
        <div className="container-xl">
          <motion.div initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.7 }}
            className="text-center mb-10">
            <div className="label-tag mx-auto mb-4 w-fit border-white/20 text-white/70 bg-white/10">
              <MapPin className="w-4 h-4" /> Infrastructure
            </div>
            <h2 className="heading-lg text-white mb-2">Related <span style={{ color: cat.color }}>Facilities</span></h2>
          </motion.div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-5">
            {cat.facilities.map((f, i) => (
              <motion.div key={i}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                whileHover={{ y: -4, scale: 1.03 }}
                className="p-5 rounded-2xl text-center"
                style={{ background: `${cat.color}10`, border: `1px solid ${cat.color}25` }}>
                <div className="text-3xl mb-3">{f.emoji}</div>
                <div className="text-white font-semibold text-sm mb-1">{f.name}</div>
                <div className="text-xs" style={{ color: `${cat.color}aa` }}>{f.type}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── BOTTOM NAVIGATION ─── */}
      <section className="py-12 px-4" style={{ background: '#050d1a' }}>
        <div className="container-lg">
          <div className="flex flex-col sm:flex-row gap-4 justify-between items-center">
            <Link href="/waste-categories" className="btn-crystal btn-crystal-glass text-white border-white/20">
              <ArrowLeft className="w-4 h-4" /> All Categories
            </Link>
            <div className="flex gap-4">
              <Link href="/five-rs" className="btn-crystal btn-crystal-outline">
                The 5 R's Guide
              </Link>
              <Link href="/recycling-process" className="btn-crystal btn-crystal-primary">
                Recycling Process <Recycle className="w-4 h-4" />
              </Link>
            </div>
          </div>
        </div>
      </section>

    </main>
  );
}
